[package]
name = "lineq"
version = "0.1.1"
license = "MIT"
description = "Linear algebra library"
repository = "https://github.com/Ethan-Metz/lineq/"
readme = "README.md"
keywords = ["lineq", "linq", "linear-algebra", "vector", "matrix"]
categories = ["mathematics"]
